### ISSUE TITLE
Properly handle mapping error from logservice configuration file

### ISSUE THREAD

**Issue by f-guichard** [orange-cloudfoundry/logs-service-broker#7]
We had an issue where a bosh operator had unproperly set mandatory variables.

While the error is on user-side, the error seems unproperly handle un logservice-broker because it made the main program panic, and bos operateur, unfamiliar with golang semantics, was helpless.

It would be nice if those errors were properly caught, if possible.

**Comment by ArthurHlt** [comment]
panic is always made intentionally in golang, depending on what was the error (the first line is always an error message and the rest of message is a very common stack trace in general), it can have pre-check before to not coming inside this panic. 

you can have an example of panic message (which always form like that) here: https://play.golang.org/p/9_Jl9G-kFBM . Note the `panic: toto` where `toto` is the content i have put in the panic.

Here, it don't know what was the error you had, so I can't make pre-check for not panic or even whether or not I can do a pre-check for it in your context.

Feel free to re-open if you can this error message
